### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Sobihan** [Sobihan/Json_To_Browser#1]
Have to fix a bug.

**Comment by fanfan54** [comment]
Do you mean a segfault?

**Comment by Sobihan** [comment]
> Do you mean a segfault?

Yes of course.

**Comment by Sobihan** [comment]
There is no problem my friend. I remove all segfault 👍

**Comment by fanfan54** [comment]
You're a genius my friend ( ͡° ͜ʖ ͡°)

**Comment by fanfan54** [comment]
You're a better coder than @williamdu93
